### ISSUE TITLE
Runtime warning on example file

### ISSUE THREAD

**Issue by itamblyn** [jmcelve2/cheshire#2]
telemachos:examples itamblyn$ python example.py
/Users/itamblyn/anaconda3/lib/python3.6/site-packages/cheshire/ParamSampler.py:177: RuntimeWarning: invalid value encountered in sqrt
  l_y = 1 / np.sqrt((2*energy)/math.pi**2 - 1/l_x**2)

Running on OS X

**Comment by jmcelve2** [comment]
This happens when `(2*energy)/math.pi**2` is less than `1/l_x**2`. This doesn't actually break anything because sanity checks are done on `l_x` and `l_y` after the sampling to ensure the values are legitimate, but seeing the runtime warning is probably disconcerting for a user. I'll add a check so that the warning can't be generated.
